added hibernate.enable_lazy_load_no_trans property to config
cause of exception:
org.hibernate.LazyInitializationException: could not initialize proxy -
no Session